module.exports=[
    {
        type:"delete",
        url:"/user/delete"
    },{
        type:"add",
        url:"/user/add"
    },{
        type:"edit",
        url:"/user/edit"
    },{
        type:"add",
        url:'/role/add'
    }
]